blank_issues_enabled: false
contact_links:
  - name: Canal de Dúvidas / Discussões
    url: https://github.com/orgs/GTEC-IFRO/discussions
    about: Utilize para perguntas gerais que não representem bugs ou novas implementações.
